version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: om-frontend
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: production
    networks:
      - om-frontend-net
      - proxy-net

networks:
  om-frontend-net:
    driver: bridge
  proxy-net:
    external: true
    name: chamran-frontend_proxy-network
